src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $illustration = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column]
    private ?float $tva = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getIllustration(): ?string
    {
        return $this->illustration;
    }

    public function setIllustration(string $illustration): static
    {
        $this->illustration = $illustration;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceWt(){
        $coeff = 1+ ($this->tva/100);

        return $coeff * $this->price;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Classe\Cart;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class CartController extends AbstractController
{
    #[Route('/mon-panier', name: 'app_cart')]
    public function index(Cart $cart): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => $cart->getCart(),
            'totalWt' => $cart->getTotalWt()
        ]);
    }

    #[Route('/cart/add/{id}', name: 'app_cart_add')]
    public function add($id, Cart $cart, ProductRepository $productRepository, Request $request): Response
    {
        $product = $productRepository->findOneById($id);
      
        $cart->add($product);
        
        $this->addFlash(
            'success', 
            "Le produit ".$product->getName()." a été correctement ajouté au panier"
        );
        return $this->redirect($request->headers->get('referer'));
        
    }


    #[Route('/cart/decrease/{id}', name: 'app_cart_decrease')]
    public function decrease($id, Cart $cart): Response
    {
      
        $cart->decrease($id);
        
        $this->addFlash(
            'success', 
            "Le produit a été correctement supprimé du panier"
        );
        return $this->redirectToRoute('app_cart');
        
    }

    #[Route('/cart/remove', name: 'app_cart_remove')]
    public function remove(Cart $cart): Response
    {
        
        $cart->remove();
        
        return $this->redirectToRoute('app_home');
        
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container my-5">
		<h1>Mon panier</h1>

		<div class="row">
			<div class="col-md-8">
				{% for product in cart %}
					<div class="row mt-2">
						<div class="col-md-2">
							<img src="/uploads/{{ product.object.illustration }}" class="img-fluid" alt="{{ product.object.name }}">
						</div>

						<div class="col-md-6">
							<strong>{{ product.object.priceWt | priceInEuro }}</strong>
						</div>

						<div class="col-md-2 text-right d-flex align-items-center gap-2">
							<a href="{{ path('app_cart_decrease', {id : product.object.id}) }}" class="btn btn-primary rounded-circle d-flex justify-content-center align-items-center" style="width: 25px; height: 25px;">
								-
							</a>

							<span class="badge text-bg-dark">{{ product.quantity }}</span>

							<a href="{{ path('app_cart_add', {id : product.object.id}) }}" class="btn btn-primary rounded-circle d-flex justify-content-center align-items-center" style="width: 25px; height: 25px;">
								+
							</a>
						</div>


						<div class="col-md-2">
							<strong>{{ (product.object.priceWt * product.quantity) | priceInEuro }}</strong>
						</div>
					</div>
				{% endfor %}

				{% if cart | length > 0 %}
					<a href="{{ path('app_cart_remove') }}" class="small d-block mt-3">
					Vider le panier
				</a>
				{% endif %}
				
			</div>
			<div class="col-md-4">
				<div class="bg-light p-3">
					<div class="d-flex justify-content-between">
						<span class="fw-bold">Total Produit</span>
						<span class="fw-bold ">{{ fullCartQuantity}}</span>
					</div>

					<div class="d-flex justify-content-between mt-3 ">
						<span class="fw-bold">Prix Total</span>
						<span class="fw-bold">{{totalWt | priceInEuro}}</span>
					</div>

					<div>
						<a href="#" class="btn btn-success w-100 mt-3">Commander</a>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}